### ISSUE TITLE
Facing mobile responsive issue with this pluging, please help to fix this issue.

### ISSUE THREAD

**Issue by nirmal-technotackle** [DaveAldon/Easy-PDF#1]
Hi this is an awesome plugin and it's realy helpful for us. But am facing some issue in the mobile responsive. And I tried to fix that but the pdf is not readable in that. So am attaching all screenshots of those issues. Please help us to fix this issue. 

Mobile view
![mobile1](https://user-images.githubusercontent.com/39582548/92687492-45635c80-f359-11ea-935d-a38a32e0b59a.png)

Desktop view
![image](https://user-images.githubusercontent.com/39582548/92687557-63c95800-f359-11ea-87b5-957a02878a4f.png)

Mobile view which we tried to fix
![image](https://user-images.githubusercontent.com/39582548/92687595-7ba0dc00-f359-11ea-8e96-7b876328a9ee.png)

Thanks in advance.

**Comment by DaveAldon** [comment]
Hello,

If you set a CSS rule like this:

```
#pdfview {
   width: 100%;
}
```

Does that make the pdf canvas fit the mobile window you're making? Right now it's explicitly set with an inline rule to be 400 height & 400 width. If that's not what you want, what exactly do you want it to look like?

**Comment by nirmal-technotackle** [comment]
Thanks a lot. I was testing this in my google chrome so that's why mobile view text is not much readable now I tested it in my mobile and it's enough to read.
